name: 'Troubleshooting'

on:
  workflow_dispatch:
    inputs:
      displayNameOfSecrets:
        description: Display the name (not the value) of secrets available to the repository
        type: boolean
        default: false

permissions:
  contents: read
  actions: read

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Troubleshooting:
    name: freddydk/AL-Go/Actions/TroubleShooting@checkSecrets
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Troubleshooting
        uses: freddydk/AL-Go/Actions/TroubleShooting@checkSecrets
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          displayNameOfSecrets: ${{ github.event.inputs.displayNameOfSecrets }}
